// GEOs supported by the "RSOC article generation Webhook" n8n workflow.
// Format is "Name (XX)" — the workflow extracts the ISO code via regex /\(([A-Z]+)\)$/,
// so the (XX) suffix is REQUIRED. Keep this list in sync with the n8n GEO dropdown.
export const ARTICLE_GEOS: string[] = [
  'United States (US)',
  'Brazil (BR)',
  'Mexico (MX)',
  'United Kingdom (UK)',
  'France (FR)',
  'Colombia (CO)',
  'Italy (IT)',
  'Argentina (AR)',
  'Spain (ES)',
  'Germany (DE)',
  'Peru (PE)',
  'Poland (PL)',
  'Ukraine (UA)',
  'Venezuela (VE)',
  'Chile (CL)',
  'Ecuador (EC)',
  'Romania (RO)',
  'Netherlands (NL)',
  'Guatemala (GT)',
  'Dominican Republic (DO)',
  'Bolivia (BO)',
  'Portugal (PT)',
  'Belgium (BE)',
  'Sweden (SE)',
  'Hungary (HU)',
  'Greece (GR)',
  'Czechia (CZ)',
  'Austria (AT)',
  'Paraguay (PY)',
  'Honduras (HN)',
  'Switzerland (CH)',
  'Denmark (DK)',
  'Bulgaria (BG)',
  'El Salvador (SV)',
  'Costa Rica (CR)',
  'Finland (FI)',
  'Norway (NO)',
  'Ireland (IE)',
  'Slovakia (SK)',
  'Nicaragua (NI)',
  'Uruguay (UY)',
  'Panama (PA)',
  'Puerto Rico (PR)',
  'Croatia (HR)',
  'Lithuania (LT)',
  'Slovenia (SI)',
  'Latvia (LV)',
  'Estonia (EE)',
];

export const GEOS: string[] = [
  // Tier 1 — Anglosphere
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'New Zealand',
  'Ireland',
  // Tier 2 — Western Europe
  'Germany',
  'France',
  'Italy',
  'Spain',
  'Portugal',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  // Tier 3 — Nordics
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Iceland',
  // Tier 4 — CEE / Balkans
  'Poland',
  'Czech Republic',
  'Slovakia',
  'Hungary',
  'Romania',
  'Bulgaria',
  'Croatia',
  'Serbia',
  'Slovenia',
  'Bosnia and Herzegovina',
  'Albania',
  // Tier 5 — Mediterranean + Turkey
  'Greece',
  'Turkey',
  // Tier 6 — LATAM
  'Mexico',
  'Brazil',
  'Argentina',
  'Colombia',
  'Chile',
  'Peru',
  // Tier 7 — APAC
  'Japan',
  'South Korea',
  'Singapore',
  'Hong Kong',
  'Taiwan',
  // Tier 8 — MENA
  'United Arab Emirates',
  'Israel',
  'Saudi Arabia',
];
