// GEOs supported by the "RSOC article generation Webhook" n8n workflow.
// Format is "Name (XX)" — the workflow extracts the ISO code via regex /\(([A-Z]+)\)$/,
// so the (XX) suffix is REQUIRED. Keep this list in sync with the n8n GEO dropdown.
export const ARTICLE_GEOS: string[] = [
  'Afghanistan (AF)',
  'Albania (AL)',
  'Algeria (DZ)',
  'American Samoa (AS)',
  'Andorra (AD)',
  'Angola (AO)',
  'Anguilla (AI)',
  'Antigua and Barbuda (AG)',
  'Argentina (AR)',
  'Armenia (AM)',
  'Aruba (AW)',
  'Australia (AU)',
  'Austria (AT)',
  'Azerbaijan (AZ)',
  'Bahamas (BS)',
  'Bahrain (BH)',
  'Bangladesh (BD)',
  'Barbados (BB)',
  'Belarus (BY)',
  'Belgium (BE)',
  'Belize (BZ)',
  'Benin (BJ)',
  'Bermuda (BM)',
  'Bhutan (BT)',
  'Bolivia (BO)',
  'Bosnia and Herzegovina (BA)',
  'Botswana (BW)',
  'Brazil (BR)',
  'Brunei Darussalam (BN)',
  'Bulgaria (BG)',
  'Burkina Faso (BF)',
  'Burundi (BI)',
  'Cambodia (KH)',
  'Cameroon (CM)',
  'Canada (CA)',
  'Cape Verde (CV)',
  'Cayman Islands (KY)',
  'Central African Republic (CF)',
  'Chad (TD)',
  'Chile (CL)',
  'China (CN)',
  'Christmas Island (CX)',
  'Cocos (Keeling) Islands (CC)',
  'Colombia (CO)',
  'Comoros (KM)',
  'Congo (CG)',
  'Congo, the Democratic Republic of the (CD)',
  'Cook Islands (CK)',
  'Costa Rica (CR)',
  'Cote D\'ivoire (CI)',
  'Croatia (HR)',
  'Cuba (CU)',
  'Cyprus (CY)',
  'Czech Republic (CZ)',
  'Denmark (DK)',
  'Djibouti (DJ)',
  'Dominica (DM)',
  'Dominican Republic (DO)',
  'Ecuador (EC)',
  'Egypt (EG)',
  'El Salvador (SV)',
  'Equatorial Guinea (GQ)',
  'Eritrea (ER)',
  'Estonia (EE)',
  'Ethiopia (ET)',
  'Falkland Islands (Malvinas) (FK)',
  'Faroe Islands (FO)',
  'Fiji (FJ)',
  'Finland (FI)',
  'France (FR)',
  'French Guiana (GF)',
  'French Polynesia (PF)',
  'Gabon (GA)',
  'Gambia (GM)',
  'Georgia (GE)',
  'Germany (DE)',
  'Ghana (GH)',
  'Gibraltar (GI)',
  'Greece (GR)',
  'Greenland (GL)',
  'Grenada (GD)',
  'Guadeloupe (GP)',
  'Guam (GU)',
  'Guatemala (GT)',
  'Guinea (GN)',
  'Guinea-Bissau (GW)',
  'Guyana (GY)',
  'Haiti (HT)',
  'Holy See (Vatican City State) (VA)',
  'Honduras (HN)',
  'Hong Kong (HK)',
  'Hungary (HU)',
  'Iceland (IS)',
  'India (IN)',
  'Indonesia (ID)',
  'Iran, Islamic Republic of (IR)',
  'Iraq (IQ)',
  'Ireland (IE)',
  'Israel (IL)',
  'Italy (IT)',
  'Jamaica (JM)',
  'Japan (JP)',
  'Jordan (JO)',
  'Kazakhstan (KZ)',
  'Kenya (KE)',
  'Kiribati (KI)',
  'North Korea (KP)',
  'South Korea (KR)',
  'Kuwait (KW)',
  'Kyrgyzstan (KG)',
  'Lao People\'s Democratic Republic (LA)',
  'Latvia (LV)',
  'Lebanon (LB)',
  'Lesotho (LS)',
  'Liberia (LR)',
  'Libya (LY)',
  'Liechtenstein (LI)',
  'Lithuania (LT)',
  'Luxembourg (LU)',
  'Macao (MO)',
  'North Macedonia (MK)',
  'Madagascar (MG)',
  'Malawi (MW)',
  'Malaysia (MY)',
  'Maldives (MV)',
  'Mali (ML)',
  'Malta (MT)',
  'Marshall Islands (MH)',
  'Martinique (MQ)',
  'Mauritania (MR)',
  'Mauritius (MU)',
  'Mayotte (YT)',
  'Mexico (MX)',
  'Micronesia, Federated States of (FM)',
  'Moldova, Republic of (MD)',
  'Monaco (MC)',
  'Mongolia (MN)',
  'Montserrat (MS)',
  'Morocco (MA)',
  'Mozambique (MZ)',
  'Myanmar (MM)',
  'Namibia (NA)',
  'Nauru (NR)',
  'Nepal (NP)',
  'Netherlands (NL)',
  'New Caledonia (NC)',
  'New Zealand (NZ)',
  'Nicaragua (NI)',
  'Niger (NE)',
  'Nigeria (NG)',
  'Niue (NU)',
  'Norfolk Island (NF)',
  'Northern Mariana Islands (MP)',
  'Norway (NO)',
  'Oman (OM)',
  'Pakistan (PK)',
  'Palau (PW)',
  'Palestinian Territory, Occupied (PS)',
  'Panama (PA)',
  'Papua New Guinea (PG)',
  'Paraguay (PY)',
  'Peru (PE)',
  'Philippines (PH)',
  'Pitcairn (PN)',
  'Poland (PL)',
  'Portugal (PT)',
  'Puerto Rico (PR)',
  'Qatar (QA)',
  'Reunion (RE)',
  'Romania (RO)',
  'Russian Federation (RU)',
  'Rwanda (RW)',
  'Saint Helena (SH)',
  'Saint Kitts and Nevis (KN)',
  'Saint Lucia (LC)',
  'Saint Pierre and Miquelon (PM)',
  'Saint Vincent and the Grenadines (VC)',
  'Samoa (WS)',
  'San Marino (SM)',
  'Sao Tome and Principe (ST)',
  'Saudi Arabia (SA)',
  'Senegal (SN)',
  'Serbia and Montenegro (RS)',
  'Seychelles (SC)',
  'Sierra Leone (SL)',
  'Singapore (SG)',
  'Slovakia (SK)',
  'Slovenia (SI)',
  'Solomon Islands (SB)',
  'Somalia (SO)',
  'South Africa (ZA)',
  'Spain (ES)',
  'Sri Lanka (LK)',
  'Sudan (SD)',
  'Suriname (SR)',
  'Svalbard and Jan Mayen (SJ)',
  'Swaziland (SZ)',
  'Sweden (SE)',
  'Switzerland (CH)',
  'Syrian Arab Republic (SY)',
  'Taiwan (TW)',
  'Tajikistan (TJ)',
  'Tanzania, United Republic of (TZ)',
  'Thailand (TH)',
  'Timor-Leste (TL)',
  'Togo (TG)',
  'Tokelau (TK)',
  'Tonga (TO)',
  'Trinidad and Tobago (TT)',
  'Tunisia (TN)',
  'Turkey (TR)',
  'Turkmenistan (TM)',
  'Turks and Caicos Islands (TC)',
  'Tuvalu (TV)',
  'Uganda (UG)',
  'Ukraine (UA)',
  'United Arab Emirates (AE)',
  'United Kingdom (UK)',
  'United States (US)',
  'Uruguay (UY)',
  'Uzbekistan (UZ)',
  'Vanuatu (VU)',
  'Venezuela (VE)',
  'Viet Nam (VN)',
  'Virgin Islands, British (VG)',
  'Virgin Islands, U.S. (VI)',
  'Wallis and Futuna (WF)',
  'Western Sahara (EH)',
  'Yemen (YE)',
  'Zambia (ZM)',
  'Zimbabwe (ZW)',
  'Guernsey (GG)',
  'Jersey (JE)',
  'Isle of Man (IM)',
  'Montenegro (ME)',
];

// GEOs + languages for the "Keyword Studio" n8n workflow. Values come from KeywordTool's
// own `country` / `language` parameter tables. The workflow's Init State forwards them
// straight to the KeywordTool API, so the codes must match KeywordTool exactly.
//
// Each country exposes only the languages that make sense for it (e.g. Switzerland →
// German / French / Italian), and the FIRST one is the default. Where KeywordTool offers
// a country-specific locale (de-CH, pt-BR, zh-TW, ar-AE…) we use it; otherwise we fall
// back to the base language code.
export interface KeywordLanguage {
  name: string;   // shown in the dropdown / fed to the LLM prompt
  code: string;   // value sent to KeywordTool, e.g. "de-CH" or "en"
}

export interface KeywordGeo {
  name: string;                  // shown in the dropdown
  country: string;               // KeywordTool country code (ISO 3166 alpha-2)
  languages: KeywordLanguage[];  // relevant languages; [0] is the default
}

// Base language name → { stem, fallback }. `stem` is combined with a country code to
// look up a locale variant in LOCALE_CODES; `fallback` is used when no variant exists.
// Note KeywordTool quirks: Hebrew is "iw", Chinese/Portuguese have no plain base code.
const LANG_STEMS: Record<string, { stem: string; fallback: string }> = {
  English: { stem: 'en', fallback: 'en' },
  Spanish: { stem: 'es', fallback: 'es' },
  // KeywordTool's regional "Español (Latinoamérica)" — used as the default for LATAM GEOs.
  'Spanish (Latin America)': { stem: 'es-419', fallback: 'es-419' },
  Portuguese: { stem: 'pt', fallback: 'pt-PT' },
  French: { stem: 'fr', fallback: 'fr' },
  German: { stem: 'de', fallback: 'de' },
  Italian: { stem: 'it', fallback: 'it' },
  Dutch: { stem: 'nl', fallback: 'nl' },
  Swedish: { stem: 'sv', fallback: 'sv' },
  Norwegian: { stem: 'no', fallback: 'no' },
  Danish: { stem: 'da', fallback: 'da' },
  Finnish: { stem: 'fi', fallback: 'fi' },
  Icelandic: { stem: 'is', fallback: 'is' },
  Polish: { stem: 'pl', fallback: 'pl' },
  Czech: { stem: 'cs', fallback: 'cs' },
  Slovak: { stem: 'sk', fallback: 'sk' },
  Hungarian: { stem: 'hu', fallback: 'hu' },
  Romanian: { stem: 'ro', fallback: 'ro' },
  Bulgarian: { stem: 'bg', fallback: 'bg' },
  Croatian: { stem: 'hr', fallback: 'hr' },
  Serbian: { stem: 'sr', fallback: 'sr' },
  Slovenian: { stem: 'sl', fallback: 'sl' },
  Bosnian: { stem: 'bs', fallback: 'bs' },
  Macedonian: { stem: 'mk', fallback: 'mk' },
  Albanian: { stem: 'sq', fallback: 'sq' },
  Estonian: { stem: 'et', fallback: 'et' },
  Latvian: { stem: 'lv', fallback: 'lv' },
  Lithuanian: { stem: 'lt', fallback: 'lt' },
  Greek: { stem: 'el', fallback: 'el' },
  Turkish: { stem: 'tr', fallback: 'tr' },
  Ukrainian: { stem: 'uk', fallback: 'uk' },
  Russian: { stem: 'ru', fallback: 'ru' },
  Belarusian: { stem: 'be', fallback: 'be' },
  Georgian: { stem: 'ka', fallback: 'ka' },
  Armenian: { stem: 'hy', fallback: 'hy' },
  Azerbaijani: { stem: 'az', fallback: 'az' },
  Kazakh: { stem: 'kk', fallback: 'kk' },
  Kyrgyz: { stem: 'ky', fallback: 'ky' },
  Uzbek: { stem: 'uz', fallback: 'uz' },
  Tajik: { stem: 'tg', fallback: 'tg' },
  Turkmen: { stem: 'tk', fallback: 'tk' },
  Mongolian: { stem: 'mn', fallback: 'mn' },
  Japanese: { stem: 'ja', fallback: 'ja' },
  Korean: { stem: 'ko', fallback: 'ko' },
  Chinese: { stem: 'zh', fallback: 'zh-CN' },
  Hindi: { stem: 'hi', fallback: 'hi' },
  Bengali: { stem: 'bn', fallback: 'bn' },
  Urdu: { stem: 'ur', fallback: 'ur' },
  Punjabi: { stem: 'pa', fallback: 'pa' },
  Tamil: { stem: 'ta', fallback: 'ta' },
  Telugu: { stem: 'te', fallback: 'te' },
  Nepali: { stem: 'ne', fallback: 'ne' },
  Sinhala: { stem: 'si', fallback: 'si' },
  Indonesian: { stem: 'id', fallback: 'id' },
  Malay: { stem: 'ms', fallback: 'ms' },
  Filipino: { stem: 'tl', fallback: 'tl' },
  Thai: { stem: 'th', fallback: 'th' },
  Vietnamese: { stem: 'vi', fallback: 'vi' },
  Khmer: { stem: 'km', fallback: 'km' },
  Lao: { stem: 'lo', fallback: 'lo' },
  Burmese: { stem: 'my', fallback: 'my' },
  Arabic: { stem: 'ar', fallback: 'ar' },
  Hebrew: { stem: 'iw', fallback: 'iw' },
  Persian: { stem: 'fa', fallback: 'fa' },
  Pashto: { stem: 'ps', fallback: 'ps' },
  Catalan: { stem: 'ca', fallback: 'ca' },
  Galician: { stem: 'gl', fallback: 'gl' },
  Basque: { stem: 'eu', fallback: 'eu' },
  Afrikaans: { stem: 'af', fallback: 'af' },
  Swahili: { stem: 'sw', fallback: 'sw' },
  Amharic: { stem: 'am', fallback: 'am' },
  Somali: { stem: 'so', fallback: 'so' },
  Chewa: { stem: 'ny', fallback: 'ny' },
  Malagasy: { stem: 'mg', fallback: 'mg' },
  Maltese: { stem: 'mt', fallback: 'mt' },
  'Haitian Creole': { stem: 'ht', fallback: 'ht' },
  Sotho: { stem: 'st', fallback: 'st' },
  Tswana: { stem: 'tn', fallback: 'tn' },
  Tongan: { stem: 'to', fallback: 'to' },
};

// Country-specific locale codes that KeywordTool actually supports (from its language table).
const LOCALE_CODES = new Set<string>([
  'ar-AE', 'ar-BH', 'ar-IQ', 'ar-JO', 'ar-KW', 'ar-LB', 'ar-LY', 'ar-OM', 'ar-PS', 'ar-QA', 'ar-SA', 'ar-TN',
  'ca-AD', 'zh-CN', 'zh-HK', 'zh-TW', 'da-GL', 'nl-BE', 'nl-SR',
  'en-AG', 'en-AI', 'en-AS', 'en-AU', 'en-BS', 'en-BT', 'en-BZ', 'en-CA', 'en-CK', 'en-CY', 'en-DM', 'en-FJ',
  'en-FM', 'en-GB', 'en-GG', 'en-GH', 'en-GI', 'en-GM', 'en-GY', 'en-IE', 'en-IM', 'en-IN', 'en-JE', 'en-JM',
  'en-KI', 'en-LK', 'en-MS', 'en-MU', 'en-MV', 'en-MY', 'en-NA', 'en-NF', 'en-NG', 'en-NR', 'en-NU', 'en-NZ',
  'en-PG', 'en-PH', 'en-PK', 'en-PN', 'en-RW', 'en-SB', 'en-SH', 'en-SL', 'en-TK', 'en-TO', 'en-TT', 'en-UG',
  'en-VC', 'en-VG', 'en-VI', 'en-VU', 'en-WS', 'en-ZA', 'en-ZM', 'en-ZW',
  'fr-BF', 'fr-BI', 'fr-BJ', 'fr-CD', 'fr-CF', 'fr-CI', 'fr-CM', 'fr-DJ', 'fr-DZ', 'fr-GA', 'fr-GP', 'fr-HT',
  'fr-MA', 'fr-ML', 'fr-NE', 'fr-SN', 'fr-TD', 'fr-TG',
  'de-AT', 'de-LI', 'de-LU', 'de-CH', 'it-SM', 'ms-BN', 'pt-BR', 'pt-PT', 'ro-MD', 'sr-ME', 'st-LS', 'sw-KE', 'tn-BW',
]);

const resolveLang = (name: string, country: string): KeywordLanguage => {
  const def = LANG_STEMS[name];
  const locale = `${def.stem}-${country}`;
  return { name, code: LOCALE_CODES.has(locale) ? locale : def.fallback };
};

// [display name, KeywordTool country code, [language names — default first]]
const GEO_DEFS: [string, string, string[]][] = [
  ['Global / Worldwide', 'GLB', ['English']],
  ['Afghanistan', 'AF', ['Persian', 'Pashto']],
  ['Albania', 'AL', ['Albanian']],
  ['Algeria', 'DZ', ['Arabic', 'French']],
  ['American Samoa', 'AS', ['English']],
  ['Andorra', 'AD', ['Catalan', 'Spanish', 'French']],
  ['Angola', 'AO', ['Portuguese']],
  ['Anguilla', 'AI', ['English']],
  ['Antigua and Barbuda', 'AG', ['English']],
  ['Argentina', 'AR', ['Spanish (Latin America)']],
  ['Armenia', 'AM', ['Armenian', 'Russian']],
  ['Australia', 'AU', ['English']],
  ['Austria', 'AT', ['German']],
  ['Azerbaijan', 'AZ', ['Azerbaijani', 'Russian']],
  ['Bahamas', 'BS', ['English']],
  ['Bahrain', 'BH', ['Arabic', 'English']],
  ['Bangladesh', 'BD', ['Bengali', 'English']],
  ['Belarus', 'BY', ['Russian', 'Belarusian']],
  ['Belgium', 'BE', ['Dutch', 'French']],
  ['Belize', 'BZ', ['English', 'Spanish (Latin America)']],
  ['Benin', 'BJ', ['French']],
  ['Bhutan', 'BT', ['English']],
  ['Bolivia', 'BO', ['Spanish (Latin America)']],
  ['Bosnia and Herzegovina', 'BA', ['Bosnian']],
  ['Botswana', 'BW', ['English', 'Tswana']],
  ['Brazil', 'BR', ['Portuguese']],
  ['British Virgin Islands', 'VG', ['English']],
  ['Brunei', 'BN', ['Malay', 'English']],
  ['Bulgaria', 'BG', ['Bulgarian']],
  ['Burkina Faso', 'BF', ['French']],
  ['Burundi', 'BI', ['French']],
  ['Cambodia', 'KH', ['Khmer', 'English']],
  ['Cameroon', 'CM', ['French', 'English']],
  ['Canada', 'CA', ['English', 'French']],
  ['Cape Verde', 'CV', ['Portuguese']],
  ['Central African Republic', 'CF', ['French']],
  ['Chad', 'TD', ['French', 'Arabic']],
  ['Chile', 'CL', ['Spanish (Latin America)']],
  ['Colombia', 'CO', ['Spanish (Latin America)']],
  ['Congo - Kinshasa', 'CD', ['French']],
  ['Cook Islands', 'CK', ['English']],
  ['Costa Rica', 'CR', ['Spanish (Latin America)']],
  ['Croatia', 'HR', ['Croatian']],
  ['Cuba', 'CU', ['Spanish (Latin America)']],
  ['Cyprus', 'CY', ['Greek', 'English', 'Turkish']],
  ['Czechia', 'CZ', ['Czech']],
  ['Côte d’Ivoire', 'CI', ['French']],
  ['Denmark', 'DK', ['Danish']],
  ['Djibouti', 'DJ', ['French', 'Arabic']],
  ['Dominica', 'DM', ['English']],
  ['Dominican Republic', 'DO', ['Spanish (Latin America)']],
  ['Ecuador', 'EC', ['Spanish (Latin America)']],
  ['Egypt', 'EG', ['Arabic', 'English']],
  ['El Salvador', 'SV', ['Spanish (Latin America)']],
  ['Estonia', 'EE', ['Estonian', 'Russian']],
  ['Ethiopia', 'ET', ['Amharic', 'English']],
  ['Fiji', 'FJ', ['English']],
  ['Finland', 'FI', ['Finnish', 'Swedish']],
  ['France', 'FR', ['French']],
  ['Gabon', 'GA', ['French']],
  ['Gambia', 'GM', ['English']],
  ['Georgia', 'GE', ['Georgian', 'Russian']],
  ['Germany', 'DE', ['German']],
  ['Ghana', 'GH', ['English']],
  ['Gibraltar', 'GI', ['English']],
  ['Greece', 'GR', ['Greek']],
  ['Greenland', 'GL', ['Danish']],
  ['Guadeloupe', 'GP', ['French']],
  ['Guernsey', 'GG', ['English']],
  ['Guyana', 'GY', ['English']],
  ['Haiti', 'HT', ['French', 'Haitian Creole']],
  ['Honduras', 'HN', ['Spanish (Latin America)']],
  ['Hong Kong', 'HK', ['Chinese', 'English']],
  ['Hungary', 'HU', ['Hungarian']],
  ['Iceland', 'IS', ['Icelandic']],
  ['India', 'IN', ['English', 'Hindi']],
  ['Indonesia', 'ID', ['Indonesian']],
  ['Iraq', 'IQ', ['Arabic']],
  ['Ireland', 'IE', ['English']],
  ['Isle of Man', 'IM', ['English']],
  ['Israel', 'IL', ['Hebrew', 'Arabic', 'English']],
  ['Italy', 'IT', ['Italian']],
  ['Jamaica', 'JM', ['English']],
  ['Japan', 'JP', ['Japanese']],
  ['Jersey', 'JE', ['English']],
  ['Jordan', 'JO', ['Arabic', 'English']],
  ['Kazakhstan', 'KZ', ['Russian', 'Kazakh']],
  ['Kenya', 'KE', ['English', 'Swahili']],
  ['Kiribati', 'KI', ['English']],
  ['Kuwait', 'KW', ['Arabic', 'English']],
  ['Kyrgyzstan', 'KG', ['Russian', 'Kyrgyz']],
  ['Laos', 'LA', ['Lao']],
  ['Latvia', 'LV', ['Latvian', 'Russian']],
  ['Lebanon', 'LB', ['Arabic', 'French']],
  ['Lesotho', 'LS', ['English', 'Sotho']],
  ['Libya', 'LY', ['Arabic']],
  ['Liechtenstein', 'LI', ['German']],
  ['Lithuania', 'LT', ['Lithuanian', 'Russian']],
  ['Luxembourg', 'LU', ['French', 'German']],
  ['Macedonia (FYROM)', 'MK', ['Macedonian']],
  ['Madagascar', 'MG', ['French', 'Malagasy']],
  ['Malawi', 'MW', ['English', 'Chewa']],
  ['Malaysia', 'MY', ['Malay', 'English']],
  ['Maldives', 'MV', ['English']],
  ['Mali', 'ML', ['French']],
  ['Malta', 'MT', ['English', 'Maltese']],
  ['Mauritius', 'MU', ['English', 'French']],
  ['Mexico', 'MX', ['Spanish (Latin America)']],
  ['Micronesia', 'FM', ['English']],
  ['Moldova', 'MD', ['Romanian', 'Russian']],
  ['Mongolia', 'MN', ['Mongolian']],
  ['Montenegro', 'ME', ['Serbian']],
  ['Montserrat', 'MS', ['English']],
  ['Morocco', 'MA', ['Arabic', 'French']],
  ['Mozambique', 'MZ', ['Portuguese']],
  ['Myanmar (Burma)', 'MM', ['Burmese']],
  ['Namibia', 'NA', ['English']],
  ['Nauru', 'NR', ['English']],
  ['Nepal', 'NP', ['Nepali']],
  ['Netherlands', 'NL', ['Dutch']],
  ['New Zealand', 'NZ', ['English']],
  ['Nicaragua', 'NI', ['Spanish (Latin America)']],
  ['Niger', 'NE', ['French']],
  ['Nigeria', 'NG', ['English']],
  ['Niue', 'NU', ['English']],
  ['Norfolk Island', 'NF', ['English']],
  ['Norway', 'NO', ['Norwegian']],
  ['Oman', 'OM', ['Arabic', 'English']],
  ['Pakistan', 'PK', ['Urdu', 'English']],
  ['Palestine', 'PS', ['Arabic']],
  ['Panama', 'PA', ['Spanish (Latin America)']],
  ['Papua New Guinea', 'PG', ['English']],
  ['Paraguay', 'PY', ['Spanish (Latin America)']],
  ['Peru', 'PE', ['Spanish (Latin America)']],
  ['Philippines', 'PH', ['English', 'Filipino']],
  ['Pitcairn Islands', 'PN', ['English']],
  ['Poland', 'PL', ['Polish']],
  ['Portugal', 'PT', ['Portuguese']],
  ['Puerto Rico', 'PR', ['Spanish (Latin America)', 'English']],
  ['Qatar', 'QA', ['Arabic', 'English']],
  ['Romania', 'RO', ['Romanian']],
  ['Rwanda', 'RW', ['English', 'French']],
  ['Samoa', 'WS', ['English']],
  ['San Marino', 'SM', ['Italian']],
  ['Saudi Arabia', 'SA', ['Arabic', 'English']],
  ['Senegal', 'SN', ['French']],
  ['Serbia', 'RS', ['Serbian']],
  ['Seychelles', 'SC', ['English', 'French']],
  ['Sierra Leone', 'SL', ['English']],
  ['Singapore', 'SG', ['English', 'Chinese', 'Malay']],
  ['Slovakia', 'SK', ['Slovak']],
  ['Slovenia', 'SI', ['Slovenian']],
  ['Solomon Islands', 'SB', ['English']],
  ['Somalia', 'SO', ['Somali', 'Arabic']],
  ['South Africa', 'ZA', ['English', 'Afrikaans']],
  ['South Korea', 'KR', ['Korean']],
  ['Spain', 'ES', ['Spanish', 'Catalan', 'Galician', 'Basque']],
  ['Sri Lanka', 'LK', ['English', 'Sinhala', 'Tamil']],
  ['St. Helena', 'SH', ['English']],
  ['St. Vincent & Grenadines', 'VC', ['English']],
  ['Suriname', 'SR', ['Dutch']],
  ['Sweden', 'SE', ['Swedish']],
  ['Switzerland', 'CH', ['German', 'French', 'Italian']],
  ['São Tomé & Príncipe', 'ST', ['Portuguese']],
  ['Taiwan', 'TW', ['Chinese']],
  ['Tajikistan', 'TJ', ['Tajik', 'Russian']],
  ['Tanzania', 'TZ', ['Swahili', 'English']],
  ['Thailand', 'TH', ['Thai']],
  ['Timor-Leste', 'TL', ['Portuguese']],
  ['Togo', 'TG', ['French']],
  ['Tokelau', 'TK', ['English']],
  ['Tonga', 'TO', ['English', 'Tongan']],
  ['Trinidad and Tobago', 'TT', ['English']],
  ['Tunisia', 'TN', ['Arabic', 'French']],
  ['Turkiye', 'TR', ['Turkish']],
  ['Turkmenistan', 'TM', ['Turkmen', 'Russian']],
  ['U.S. Virgin Islands', 'VI', ['English']],
  ['Uganda', 'UG', ['English']],
  ['Ukraine', 'UA', ['Ukrainian', 'Russian']],
  ['United Arab Emirates', 'AE', ['Arabic', 'English']],
  ['United Kingdom', 'GB', ['English']],
  ['United States', 'US', ['English', 'Spanish']],
  ['Uruguay', 'UY', ['Spanish (Latin America)']],
  ['Uzbekistan', 'UZ', ['Uzbek', 'Russian']],
  ['Vanuatu', 'VU', ['English', 'French']],
  ['Venezuela', 'VE', ['Spanish (Latin America)']],
  ['Vietnam', 'VN', ['Vietnamese']],
  ['Zambia', 'ZM', ['English']],
  ['Zimbabwe', 'ZW', ['English']],
];

export const KEYWORD_GEOS: KeywordGeo[] = GEO_DEFS.map(([name, country, langs]) => ({
  name,
  country,
  languages: langs.map((l) => resolveLang(l, country)),
}));

export const KEYWORD_GEO_NAMES: string[] = KEYWORD_GEOS.map((g) => g.name);

export const GEOS: string[] = [
  // Tier 1 — Anglosphere
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'New Zealand',
  'Ireland',
  // Tier 2 — Western Europe
  'Germany',
  'France',
  'Italy',
  'Spain',
  'Portugal',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  // Tier 3 — Nordics
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Iceland',
  // Tier 4 — CEE / Balkans
  'Poland',
  'Czech Republic',
  'Slovakia',
  'Hungary',
  'Romania',
  'Bulgaria',
  'Croatia',
  'Serbia',
  'Slovenia',
  'Bosnia and Herzegovina',
  'Albania',
  // Tier 5 — Mediterranean + Turkey
  'Greece',
  'Turkey',
  // Tier 6 — LATAM
  'Mexico',
  'Brazil',
  'Argentina',
  'Colombia',
  'Chile',
  'Peru',
  // Tier 7 — APAC
  'Japan',
  'South Korea',
  'Singapore',
  'Hong Kong',
  'Taiwan',
  // Tier 8 — MENA
  'United Arab Emirates',
  'Israel',
  'Saudi Arabia',
];
